IBM/test-infra

- prow/config.yaml
- prow/plugins.yaml
add tide auto merge plugin for repos.
Fixes #
/cc @gyliu513
```release-note
```
> add tide auto merge plugin for multicloud repos.

- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/OWNERS
To add multicloud-operators-placementrule into the prow job
Fixes #
NA
```release-note
```
> add placementrule to jobs

- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
> update build tools image.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update build tools image to add kubebuilder.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> fix incorrect kubebuilder path in build-tools image.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update build-tools && add env.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
update rerun command for couple of repos.
Fixes #
/cc @gyliu513
```release-note
```
> update rerun command.

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> add env for kubebuilder.

- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
add codecov token for oasis.
Fixes #
/cc @gyliu513
```release-note
```
> add codecov for oasis.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> add codecov got go-repo-template.

- prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> addcodecov for mcm operators repos.

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> move codecov to postsubmit.

- prow/config.yaml
onborad new repo: https://github.com/IBM/multicloud-application-monitoring-dashboard
Fixes #
/cc @gyliu513
```release-note
```
> onboard new repo.

- prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> add resource request for check job.

- prow/cluster/jobs/IBM/multicloud-operators-subscription-release/IBM.multicloud-operators-subscription-release.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription-release/OWNERS
As subscriptoin-release repo moves to prow now, adding jobs for it.
@morvencao the codecov token is 
`29c2a191-5600-4670-b5d9-78b2d7cc43cd`
Fixes #
```release-note
```
> add subscription-release repo

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update repo name.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/IBM.multicloud-operators-foundation.master.yaml
- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/OWNERS
Add mcm foundation prow job 
Fixes #
```release-note
```
> add mcm foudnation prow job

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> tune prow job configurations.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update path alias for prowjob.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
> add ssh key secrets for private repos.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
> update prow job name.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
> Add lint job in mcm foundation

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
follow up PR for https://github.com/IBM/test-infra/pull/42 to add ssh token and clone uri for the new prow job.
/cc @qiujian16
> add ssh token and clone uri for prow job.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/OWNERS
- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
adding prow job for multicloud-operators-cluster-controller to integrate with the IBM test
https://github.com/rh-ibm-synergy/multicloud-operators-cluster-controller/issues/15
```release-note
adding prow job for multicloud-operators-cluster-controller to integrate with the IBM test
```
> create prow job for multicloud-operators-cluster-controller

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
This is to add image job for mcm foundation
Fixes #
```release-note
```
> Add image build job

- prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
- prow/config.yaml
Move image build job from prow job to travis job to support multi-arch build.
Fixes #
```release-note
```
> move image build job to travis.

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update branche protection for go-repo-template.

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update branch protection context name.

- prow/config.yaml
> move to old status check context for travis.

- Makefile
- prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription-release/IBM.multicloud-operators-subscription-release.master.yaml
- prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.yaml
- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
- prow/docker/build-tools/Dockerfile
- prow/docker/build-tools/build-and-push.sh
- prow/docker/docker-in-docker/Dockerfile
- prow/docker/docker-in-docker/build-and-push.sh
- prow/docker/docker-in-docker/install.sh
- prow/docker/docker-in-docker/prow-runner.sh
Fixes #
/cc
```release-note
```
> sync build-tools docker.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Followup PR for https://github.com/IBM/test-infra/pull/56
After https://github.com/IBM/test-infra/pull/56, prowjob keep failing for the reason of `Duplicate value: \"ssh-keys-ssh-secret`
```
{"component":"plank","error":"Pod \"55c3d2c7-213c-11ea-9bf5-66524f4a6aae\" is invalid: spec.volumes[4].name: Duplicate value: \"ssh-keys-ssh-secret\"","file":"prow/plank/controller.go:507","func":"k8s.io/test-infra/prow/plank.(*Controller).syncTriggeredJob","job":"build_multicloud-operators-cluster-controller","level":"warning","msg":"Unprocessable pod.","time":"2019-12-18T02:16:02Z"}
```
Fixes #
**Specify …
> remove duplicated secret volume.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
- prow/config.yaml
> fix presets for private repos.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
- prow/config.yaml
update build image and change postsubmit build job publish images for cluster-controller prow job
Fixes #
```release-note
```
> update build image and change postsubmit build job publish images

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update tide url.

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
- prow/config.yaml
> onborad ibm-metering-operator.

- prow/cluster/jobs/IBM/ibm-metering-operator/OWNERS
Adding an owners file for the metering job to restrict those who can change it.
Fixes #
No issue
```release-note
```
> Update owners for metering prow definition

- prow/cluster/jobs/IBM/ibm-catalog-operator/OWNERS
Adding owners file for the catalog job to restrict those who can change it.
Fixes #
No issue
```release-note
```
> set_catalog_owners

- prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
- prow/config.yaml
> onboard ibm-catalog-operator.

- prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
resolve build errors for https://github.com/IBM/ibm-catalog-operator/pull/3
Fixes #
```release-note
```
> update build env fro ibm-catalog-operator.

- prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
Remove unwanted jobs for Catalog Operator
Fixes #
No Issue
```release-note
```
> Remove unwanted jobs for Catalog Operator

- prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
follow PR for https://github.com/IBM/test-infra/pull/67
Fixes #
```release-note
```
> fix docker start issue for ibm-catalog-operator build.

- prow/docker/docker-in-docker/install.sh
This will help make docker-in-docker on ppc64le.
Fixes #
```release-note
```
> Adding ppc64le build support for docker-in-docker

- prow/config.yaml
> onboard common-service-operator.

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
Fixes issue with code coverage job of the prow pipeline for ibm-metering-operator 
Fixes #
none
```release-note
```
> fix secret name of code coverage job

- prow/cluster/deploy/cherry-picker.yaml
- prow/cluster/deploy/need-rebase.yaml
- prow/cluster/deploy/starter.yaml
We need to keep revision for manifests applied in prow cluster so that we can upgrade/rollback prow components.
Fixes #
```release-note
```
> keep revision for manifests in prow cluster

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/OWNERS
it enables ibm-licensing-operator build in prow
Fixes #
```release-note
```
> added licensing prow job

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
Since we are working on the multiple build clusters, we need to add default cluster for old prow jobs.
Fixes #
```release-note
```
> add default cluster for prowjob of test-infra.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
followup PR for https://github.com/IBM/test-infra/pull/79
Fixes #
```release-note
```
> fix regex issue for prowjob configurations.

- prow/cluster/deploy/starter.yaml
> support multiple build clusters.

- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
> support multiple build clusters for oasis.

- Makefile
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
> update postsubmit prowjob for docker builder.

- prow/config.yaml
> onboard IBM/ibm-licensing-operator.

- prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
we need replace the multicloud-operators-foundation import path
Fixes #
```release-note
```
> replace rh-ibm-synergy/multicloud-operators-foundation import path

- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-cert-manager-operator/OWNERS
**What this PR does / why we need it**: 
Adds the [ibm-cert-manager-operator](https://github.com/ibm/ibm-cert-manager-operator) to this repo so PROW will be triggered by it.
Fixes #
```release-note
```
> Add the cert-manager-operator to be integrated into prow.

- prow/config.yaml
followup PR for https://github.com/IBM/test-infra/pull/89
Since quay.io start to support Docker Manifest Version 2 Schema 2.
Fixes #
```release-note
```
> using utility images from quay.io

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
- prow/config.yaml
Fixes #
/cc 
```release-note
```
> use prow to build go-repo-template.

- prow/config.yaml
> onboard IBM/ibm-cert-manager-operator.

- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
- prow/config.yaml
> onboard IBM/ibm-iam-operator.

- prow/cluster/jobs/IBM/healthcheck-service-operator/IBM.healthcheck-service-operator.master.yaml
- prow/config.yaml
> onboard healthcheck-service-operator.

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
- prow/config.yaml
> onboard ibm-auditlogging-operator.

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
- prow/config.yaml
> onboard ibm-commonui-operator.

- prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-helm-api-operator/OWNERS
> onboard ibm-helm-api-operator

- prow/cluster/jobs/IBM/ibm-management-repo-operator/IBM.ibm-management-repo-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-repo-operator/OWNERS
> onboard ibm-management-repo-operator

- prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-helm-repo-operator/OWNERS
> onboard ibm-helm-repo-operator

- prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
- prow/config.yaml
> onaboard ibm-mongodb-operator.

- prow/config.yaml
Fixes #
/cc @gyliu513 @clyang82
```release-note
```
> config tide for new repos.

- prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-repo-operator/IBM.ibm-management-repo-operator.master.yaml
> Update the prow jobs for ibm helm rep operators

- prow/cluster/jobs/IBM/ingress-nginx-operator/IBM.ingress-nginx-operator.master.yaml
- prow/cluster/jobs/IBM/management-ingress-operator/IBM.management-ingress-operator.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513 
```release-note
```
> onaboard management ingress and nginx ingress repo.

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513 @haoqing0110
```release-note
```
> update repo name for ibm-healthcheck-operator.

- prow/plugins.yaml
Fixes #
/cc @gyliu513
```release-note
```
> add more plugins to manage github issues.

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> update name for two ingress repos.

- prow/config.yaml
Fixes #
/cc
```release-note
```
> fix tide cinfigurations for two ingress repos.

- prow/cluster/jobs/IBM/ibm-catalog-operator/OWNERS
- prow/cluster/jobs/IBM/ibm-cloudctl-operator/OWNERS
Updating OWNERS files with my ID for catalog and cloudctl operators. Need access to onboard those operators to meta-operator
Fixes #
```release-note
NONE
```
> added myself to OWNERS for catalog and cloudctl operators

- prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> onboard monitoring operator repos

- prow/docker/docker-in-docker/Dockerfile.s390x
- prow/docker/docker-in-docker/install.sh
Fixes #
/cc 
```release-note
```
> add docker-in-docker s390 support.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
- prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
add experimental build on s390x cluster.
/hold
**do-not-merge until the following images are ready on s390x:**
- clonerefs
- initupload
- sidecar
- entrypoint
support build on s390x cluster.
Fixes #
/cc @gyliu513 
```release-note
```
> support build on s390x cluster.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> onnoard IBM/ibm-platform-api-operator.

- prow/plugins.yaml
> enable more plugins for multicloudlab org.

- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
- prow/config.yaml
Fixes #
/cc 
```release-note
```
> onboard ibm-elastic-stack-operator.

- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
Fixes #
/cc 
```release-note
```
> update prowjobs for ibm-elastic-stack-operator.

- prow/dockerfiles/Dockfile.clonerefs
- prow/dockerfiles/Dockfile.entrypoint
- prow/dockerfiles/Dockfile.initupload
- prow/dockerfiles/Dockfile.sidecar
Fixes #
/cc 
```release-note
```
> add dockerfiles.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Fixes #
/cc
```release-note
```
> add docker for build stage.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc
```release-note
```
> support real multi-arch build for go-repo-template.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc 
```release-note
```
> update multi-arch build for go-repo-template.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc 
```release-note
```
> remove unused secrets.

- prow/docker/build-tools/Dockerfile
This will make boot-tools image build on power
Fixes #
```release-note
```
> ppc64le support for build-tool

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Fixes #
/cc 
```release-note
```
> update prow job for build tools.

- Makefile
- common/scripts/multiarch_image.sh
- prow/docker/build-tool/Dockerfile.amd64
- prow/docker/build-tool/Dockerfile.ppc64le
- prow/docker/build-tool/Dockerfile.s390x
- prow/docker/build-tool/install.sh
- prow/docker/check-tool/Dockerfile
Fixes #
/cc 
```release-note
```
> fix build tools.

- prow/docker/check-tool/Dockerfile
Fixes #
/cc 
```release-note
```
> fix check tool build.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Fixes #
/cc @gyliu513 
```release-note
```
> update prow job for build-tool multiarch image.

- prow/docker/build-tool/Dockerfile.amd64
- prow/docker/build-tool/Dockerfile.ppc64le
- prow/docker/build-tool/Dockerfile.s390x
> fix build-tool image build.

- Makefile
Fixes #
/cc
```release-note
```
> fix build-tools image tag.

- prow/docker/build-tool/Dockerfile.ppc64le
- prow/docker/build-tool/build-and-push.sh
- prow/docker/check-tool/build-and-push.sh
Fixes #
/cc
```release-note
```
> fix build-tools image build on ppc64le.

- prow/docker/build-tool/Dockerfile.ppc64le
Fixes #
/cc 
```release-note
```
> revert built-tool ppc64le image.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc @gyliu513 
```release-note
```
> update build-tool images for prow jobs.

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> add more tools to build tools images.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc 
```release-note
```
> update build-tool image version for prow jobs.

- prow/docker/build-tool/Dockerfile
Fixes #
/cc @gyliu513
```release-note
```
> fix docker in docker settings.

- prow/docker/build-tool/Dockerfile
Fixes #
/cc @gyliu513 
```release-note
```
> fix docker-in-docker storage issue.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
> update build-tool image version.

- prow/config.yaml
Try to fix: https://github.com/IBM/go-repo-template/issues/71
Fixes https://github.com/IBM/go-repo-template/issues/71
/cc @gyliu513
```release-note
```
> update details link for prow job.

- prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
- prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
- prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
Fixes #
/cc @gyliu513 
```release-note
```
> onaborad hybrid repos.

- prow/config.yaml
Fixes #
/cc @gyliu513
```release-note
```
> config tide for hybrid repos.

- prow/cluster/jobs/IBM/ibm-grafana-operator/IBM.ibm-grafana-operator.master.yaml
- prow/config.yaml
Fixes #
/cc 
```release-note
```
> onboard repo ibm-grafana-operator.

- prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
Fixes #
/cc @gyliu513
```release-note
```
> fix postsubmit build for ibm-helm-repo-operator.

- prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
Helm API and Catalog UI operators have the same build issues as Helm API, which got fixed in #154 
Fixes #
```release-note
NONE
```
> Postsubmit builds

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Fixes #
/cc 
```release-note
```
> add codecov prosubmit check.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
> Revert "add codecov prosubmit check."

- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
> add multiarch_build for ibm-management-ingress-operator.

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operatormaster.yaml
- prow/config.yaml
Fixes #
/cc @gyliu513 @chenzhiwei
```release-note
```
> onboard ibm-common-service-operator.

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.1.yaml
I open this PR for enabling PROW for release branches for ODLM.
When the code is merged into ODLM release branch, PROW will build the image with the release version.
Fixes #
/assign @morvencao 
```release-note
NONE
```
> watch release branch of ODLM

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.5.yaml
**What this PR does / why we need it**: need build for maintenance branch
Fixes #
```release-note
```
> add prow build for metering 35 maintenance

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.release-3.5.yaml
**What this PR does / why we need it**: need build for maintenance branch
Fixes #
```release-note
```
> add prow build for auditlogging 35 maintenance

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
- prow/config.yaml
- prow/plugins.yaml
Fixes #
/cc @gyliu513
```release-note
```
> onboard new repos for hybridapp-io org.

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
Fixes #
/cc 
```release-note
```
> remove power and z tests for hybridapp-io.

- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhookmaster.yaml
Add prow job for https://github.com/IBM/ibm-common-service-webhook
```release-note
NONE
```
> Add ibm-common-service-webhook

- prow/config.yaml
follow up for https://github.com/IBM/test-infra/pull/167
Fixes #
```release-note
```
> add tide config for ibm-common-service-webhook.

- prow/config.yaml
> add tide configuration for hybridapp-io repos.

- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.5.0.yaml
> add prow jobs for ibm-iam-operator release-3.5.0

- prow/config.yaml
> add tide configuration

- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/config.yaml
> onaboard hybridapp-io/ham-deploy.

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
support multiarch build for ibm-heathcheck-operator
Fixes #
```release-note
NONE
```
> ibm-heathcheck-operator multiarch build for prow

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Followup PR for https://github.com/IBM/test-infra/pull/176
> add multiarch build jobs for ibm-healthcheck-operator.

- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/config.yaml
> onboard hybridapp-io/ham-placement.

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
Enabled multiarch build for licensing operator
/cc @morvencao 
Enabling just for testing on specified branch
> enable multiarch for licensing

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
> fix image for multiarch_build_ibm-licensing-operator.

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
fixes images used by licensing image job
/cc @morvencao
> licensing - updated image for image build job

- prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
- prow/config.yaml
> onboard three new metering repos.

- prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
- prow/config.yaml
> onboard ibm-licensing-hub-operator.

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.release-1.2.yaml
> cut test branch release-1.2 for ibm-commonui-operator.

- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/config.yaml
This PR is for onboard https://github.com/IBM/ibm-secretshare-operator to the prow.
@morvencao I have added `ibm-ci-bot` as the owner of that repo. Please help to add the webhook to the repo.
Fixes #
/cc @gyliu513 @morvencao 
```release-note
```
> onboard ibm-secretshare-operator

- prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.release-3.6.yaml
> cut release-3.6 branch for ibm-helm-api-operator repo.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-3.6.yaml
> cut release branch for ibm-platform-api-operator.

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.release-0.0.1.yaml
> cut release-0.0.1 release branch for ham-application-assembler.

- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release-0.0.1.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
> cut release branch for ham-deployable-operator

- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
> fix branch regex for prow jobs.

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.release.yaml
> release-.* for hybridapp projects

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> remove build job for odlm and cs-operator.

- prow/docker/build-tool/Dockerfile
> upgrade build-tool.

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> update build-tool image for odlm.

- prow/docker/check-tool/Dockerfile
> upgrade check-tool.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
> upgrade base images for go-repo-template.

- prow/docker/build-tool/Dockerfile
> fix build-tool.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> upgrade base images.

- prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
- prow/config.yaml
> add prow job for ibm-grafana-ocpthanos-proxy.

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
previous build tool had go version 1.13.8 with vulnerabilities, new one has 1.14.6 which is ok
Fixes #
```release-note
```
> update build tool version for Healthcheck Operator

- prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
- prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
- prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
> update build-tool image.

- prow/docker/pod-utility/Dockerfile.podutilitybinaries
- prow/docker/pod-utility/Dockfile.clonerefs
- prow/docker/pod-utility/Dockfile.entrypoint
- prow/docker/pod-utility/Dockfile.initupload
- prow/docker/pod-utility/Dockfile.sidecar
- prow/docker/pod-utility/README.md
- prow/docker/pod-utility/create_utility_images.sh
- prow/docker/pod-utility/patch_bazel.diff
- prow/docker/pod-utility/patch_nodejs.diff
> add doc and tool to build pod-utility.

- prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
Need to get on V14 of go to remediate security vulnerabilities
Fixes #
```release-note
```
> move to newer build container for tool upgrades

- prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
Fixes #
@sgrube
```release-note
```
> use check-tool for check job.

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
> Remove build job for the amd64

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40261
```
image should be build-tool, not build-tools
```
> fix build tool for ibm-auditlogging-operator

- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
Need to get on V14 of go to remediate security vulnerabilities, so updating the build-tools tag
Fixes #
/cc @gyliu513 @morvencao  @clyang82
```release-note
```
> Update build tool version for ibm-cert-manager-operator

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
Missed edit on my part - need to get to go 1.14
Fixes #
```release-note
```
> update post submit container

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> upgrade golang for build-tool and check-tool.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
> update build-tool image for build-tool.

- prow/docker/build-tool/Dockerfile
> use wget to download binaries.

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
> fix check image for prow jobs.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
- prow/docker/build-tool/docker-entrypoint.sh
> fix mtu issue on ppc64le build-tool.

- Makefile
> support local build.

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
> upgrade build-tool image for prowjobs.

- prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
- prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
- prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
- prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
> upgrade build-tool and check-tool.

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> revert prowjob for ibm-monitoring-grafana-operator.

- prow/cluster/jobs/all-periodics.yaml
> remove unused periodic jobs.

- prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
> update prow job for ibm-grafana-ocpthanos-proxy.

- prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
> Revert "update prow job for ibm-grafana-ocpthanos-proxy."

- prow/cluster/jobs/IBM/prometheus-metrics-server-simulator/ibm.prometheus-metrics-server-simulator.master.yaml
- prow/config.yaml
> onboard IBM/prometheus-metrics-server-simulator.

- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.release-v3.1.5.yaml
> cut release branch v3.1.5 for elastic-stack-operator.

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
This allows our team to push changes not only to master, for example when master is freezed and we want to have separate jobs with same checks but different pushes
Fixes #
```release-note
```
> Allow development jobs

- prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
> fix incorrect path alias.

- OWNERS
> add new approver.

- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
> fix multiarch image build for ibm-elastic-stack-operator.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template-release-1.1.yaml
> update build-tool image for prowjobs.

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
> fix prow jobs for ibm-ingress-nginx-operator.

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
> update prow jobs for ibm-ingress-nginx-operator.

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.7.yaml
Fixes #
/cc @horis233
```release-note
```
> cut release-3.7 branch for the ibm-metering-operator

- OWNERS
add @ashank07 and @xcliu-ca to the reviewer and approver list.
Fixes #
```release-note
```
> add new reviewers and approvers.

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/41448
/cc @gyliu513 @morvencao @horis233 
```release-note
Use build-tool for coverage job
```
> audit - use build tool for coverage

- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
- prow/config.yaml
> Onboard new operator ibm-namespace-scope-operator

- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
> fix incorrect secret name.

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
> remove codecov test for ibm-ingress-nginx-operator.

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-4.0.yaml
> create release 4.0 branch for common-service-operator

- prow/docker/build-tool/Dockerfile
fix broken helm download link for https://github.com/IBM/test-infra/pull/260
Fixes #
```release-note
```
> fix broken helm download link.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
> update build-tool and check-tool images for go-repo-template.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
> fix incorrect check-tool image.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Reverting changes to use the new images with helm 3. Need to make changes in helm charts for helm 3 linting to pass, which is too risky right now since 4Q release is soon.
Fixes #
```release-note
NONE
```
> Revert image

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> upgrade golang version for building images.

- prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
> update building images.

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-4.0.yaml
> Correct CS4.0 release branch name for License Service

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.6.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.4.yaml
Create jobs for ibm-common-service branch release-3.6 and ODLM branch release-1.4.
Fixes #
```release-note
```
> create jobs for cs-3.6 odlm-1.4

- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.release-1.4.yaml
> management-ingress release-1.4

- prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.release-1.2.yaml
> create job for mongodb release-1.2

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-3.6.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-4.0.yaml
> Change build for CS 3.6

- prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.master.yaml
**What this PR does / why we need it**: Adds new ibm-iam-policy-operator prow job
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42110
```release-note
add ibm-iam-policy-operator
```
> add ibm-iam-policy-operator

- prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.main.yaml
**What this PR does / why we need it**: new github repos use main instead of master
Fixes #
```release-note
change ibm-iam-policy-operator branch from master to main
```
> fix: change master branch to main

- prow/config.yaml
> onboard ibm-iam-policy-operator

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> upgrade go version for build check tool images.

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-3.8.yaml
added new PROW build job for platform-api-operator EUS release (branch release-3.8)
deleted unused PROW build job for platform-api-operator release-3.6 branch
Fixes #
```release-note
NONE
```
> updated PROW build jobs for platform-api-operator

- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.0.yaml
Added PROW build for namespace scope operator EUS release CS 3.6
Fixes #
```release-note
NONE
```
> added PROW build for namespace scope operator EUS release

- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.3.yaml
Fixes #
```release-note
NONE
```
> added PROW build for secret-share operator CS 3.6 EUS release

- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.2.yaml
> added PROW build for cs-webhook CS 3.6 EUS release

- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.release-3.8.yaml
Enable prow support for eus release-3.8 for cert-manager-operator
Fixes #
/cc @horis233 @morvencao
> Enable prow support for eus release-3.8 for cert-manager-operator

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> Add comments into dockerfiles of tools

- prow/docker/check-tool/Dockerfile
> update ruby install for check-tool.

- prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.release-v3.1.5.yaml
- prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-3.8.yaml
> revert check-tool version for helm operators

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> update go version to 1.15.7

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
> test using helm 3 linting

- prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.eus.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.eus.yaml
> create monitoring eus jobs

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
> updated check tool to use helm 3 linting after PR is merged

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.release-3.8.yaml
> enable release-3.8 for auditlogging

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.7.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.3.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.1.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.4.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.5.yaml
> create 3.7 version branch for installer operators

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release.yaml
Enable release branches for Licensing
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45071
> enabled general release branches

- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
- prow/config.yaml
Enable prow build for ibm-crossplane-operator
Fixes #
```release-note
```
> enable prow build for ibm-crossplane-operator

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.release-3.8.yaml
Enable EUS stream for healthcheck operator
Fixes #
```release-note
```
> enable eus stream for healthcheck operator

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
> enable 3.11 release for grafana-operator

- prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
- prow/config.yaml
> enable prow build for ibm-crossplane

- prow/docker/build-tool/docker-entrypoint.sh
> enable experimental

- prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
> replace build image of crossplane

- prow/docker/build-tool/docker-entrypoint.sh
> set mtu for DinD

- prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
> replace build image

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> add e2e test for odlm

- prow/docker/build-tool/Dockerfile
> update operator-sdk version to 1.3.0

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> update odlm build image

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> enable ssh for internal repo

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.release-1.4.yaml
build ingress-nginx operator for EUS fixpack
> enable release-1.4 for ingress-nginx

- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.8.yaml
> fix metering multiarch build

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/config.yaml
> set private ssh key

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/config.yaml
> Set private sshkey

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/config.yaml
> create a label for ibm private repo

- prow/config.yaml
> update ssh key position

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> git redirect

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> update build images

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> add ghe in known_hosts

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> update grafana build image

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> reset dockerfiles

- prow/config.yaml
> update ssh path

- prow/config.yaml
> copy ssh to root

- prow/docker/check-tool/Dockerfile
> update ruby version

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> update check version for grafana

- prow/docker/build-tool/docker-entrypoint.sh
> enale experimental docker cli

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
> update labels use for grafana

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Updating prow to build new branches to support common services branch strategy
Fixes #
```release-note
```
> update prow job with new pipeline branches

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Only updated the first job for additional cicd branches, needed to update the remaining ones.
Fixes #
```release-note
```
> update branches for all jobs

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> update install branches

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Changes for https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47644
Fixes ##47816
/cc @ashank@us.ibm.com 
```release-note
```
> Update branches to prow build definition

- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47821
```release-note
```
> Updates to include fixes in the new pipelines

- prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
> prow enablement for monitoring branches

- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
Add support for future branch
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47886
```release-note
```
> add release-future

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
remove `release-cd` branch and add `release-future` branch
> add future branch for CS installer

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
> add release-future branch and delete release-cd branch

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Updates for building future pipeline of common ui operator
Fixes #
```release-note
```
> add release-future branch for building

- prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47644
```release-note
```
> Update MongoDB prow job branches

- prow/plugins.yaml
> disable needs-rebase

- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
> revert build images for crossplane operator

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> set preset sa in odlm e2e

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
> enable project k for cs operator

- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
> add release-k branch for iam operator

- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
> added release-k branch to cert-manager PROW build

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
> enable eus for platform api

- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
Create prow build configuration for [`IBM/crossplane-kubernetes-provider`](https://github.com/IBM/crossplane-provider-kubernetes) repo.
https://github.ibm.com/ibmprivatecloud/roadmap/issues/50564
```release-note
NONE
```
> Create configuration for Crossplane-provider-kubernetes

- prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.eus.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.eus.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.1.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.4.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.5.yaml
> remove codecov

- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
Fixes #
```release-note
NONE
```
> Change branch name for crossplane-provider-kubernetes repo to master

- prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
Our prow builds fail due to timeout. We are hoping, that setting a variable will increase the timeout.
Fixes
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50564
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51354
```release-note
```
> add `RUNNING_IN_CI` variable to pass GO linter

- prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
update due to vulnerability with Go version
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51506
```release-note
```
> Update Crossplane to use 1.17.5 Go version

- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Fixes #
/cc @horis233
```release-note
```
> change PROW build to use arch specific machines

- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> update ODLM builds

- prow/docker/check-tool/Dockerfile
> update python checker

- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
> add image pull secret to ingress nginx

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.release.yaml
> trigger hybridapp

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> bump library version for golang 1.18

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
Adding ltsr branch for Monitoring builds
Fixes #
```release-note
```
> Adding ltsr branch for Monitoring

- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
- prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Integration with LTSR pipeline
```release-note
```
> IBM Licensing Operator integration with LTSR Stream

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
> udpates for ui and ingress ltsr support

- prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
> Adding ltsr branch for installer squad

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
Integration with LTSR pipeline
Fixes #
```release-note
```
> add release-ltsr branch to build jobs

- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
> added ltsr branch to common-service-webhook builds

- prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
> Add ltsr to Servicability prow build

- prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
- prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
> add release-ltsr branch to Crossplane pipelines

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
/cc @ashank07 
```release-note
```
> tool images with golang 1.19.2 for hybridapp.io

- prow/Makefile
> update zone and cluster in Makefile

- prow/docker/build-tool/Dockerfile
> re trigger tool build after Makefile update

- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
add prowjobs for the IAM operator future branch
> add prowjobs for the IAM operator future branch

- common/scripts/config_docker.sh
Fixes #
/cc @ashank07  @pgodowski
> do not error out docker login although multicloudlab credential unknown

- prow/config.yaml
Addresses https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56077#issuecomment-50876533
> add missing volume reference for ssh key

- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
> Revert "temporarily disable grafana prow jobs (ssh key config issue)"

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
- prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.yaml
- prow/config.yaml
trying to update for the tools image build itself, we need wait after the other operators to work before validate this one
/cc @ashank07  @pgodowski
> global update tools images - for tools need tests

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-4.0.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.2.yaml
- prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.3.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.0.yaml
- prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.1.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.3.yaml
- prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.4.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.4.yaml
- prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.5.yaml
> PR for tool images installer

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
> build golang 1.20.3 tool images

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
- prow/config-s3.yaml
- prow/plugins-s3.yaml
test config updator plugin
/cc @ashank07
> test config updator plugin

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
update tool images for test-infra
> pr to update test infra images

- prow/config-s3.yaml
default namespace for prowjobs
> use ns default for prowjobs

- prow/s3/config.yaml
- prow/s3/plugins.yaml
> updatoer plugin

- prow/docker/check-tool/Dockerfile
> test pr procedure

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/plugins.yaml
- prow/s3/config.yaml
> test config updator

- prow/s3/config.yaml
for cloning from ghe as dependency
> update secrets for ghe dep by grafana

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
> test tool image build in s390 cluster

- prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
> fix hybridio tools reference

- prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
- prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
> Update hybridapp-io tool references

- prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
> Revert "Set GO111MODULE to off"

- prow/docker/build-tool/Dockerfile
- prow/docker/check-tool/Dockerfile
Update go version used in build server
> Bump go to 1.22.2

- prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
- prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
Add sc2 branch builds for cs-operator, ui, and iam
> Add first sc2 branches

- prow/config.yaml
- prow/s3/config.yaml
Config Account IAM operator into prow config.yaml
> config account iam operator

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Update commonui build for multiarch building
Fixes #
```release-note
```
> update commonui-operator for multi arch build

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
fixes yaml
Fixes #
```release-note
```
> fix commonui operator yaml

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
fix build
Fixes #
```release-note
```
> fix test jobs for commonui-operator

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
> enable post submits for commonui-operator

- prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
> Revert "Build tool image in PR (test)"

- prow/docker/build-tool/Dockerfile
> Revert "Test PR build"

- prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
> Disable ibm-commonui-operator master build
