prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml

add `export GOPRIVATE=github.com/rh-ibm-synergy` to presets for  multicloud-operator-cluster-controllers jobs to fix 
```
reading https://proxy.golang.org/github.com/rh-ibm-synergy/multicloud-operators-foundation/@v/v0.0.0-20191216172235-60e7a00eac53.mod: 410 Gone
```
Fixes https://github.com/rh-ibm-synergy/multicloud-operators-cluster-controller/issues/25
NO  …

add github.com/rh-ibm-synergy to GOPRIVATE

---

prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml

add github.ibm.com to GOPRIVATE for multicloud-operators-cluster-controller prow job
Fixes #
```release-note
add github.ibm.com to GOPRIVATE for multicloud-operators-cluster-controller prow job
```

update multicloud-operators-cluster-controller prow job

---

prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml

update cluster-operators-cluster-controller preset to add ssh secret volumn and mount for cloning private github projects
Fixes # https://github.com/rh-ibm-synergy/multicloud-operators-cluster-controller/issues/26
```release-note
update cluster-operators-cluster-controller preset to add ssh secret volumn and mount for cloning private github projects
```

add ssh secret volumn and mount to preset

---

prow/config.yaml

followup PR for https://github.com/IBM/test-infra/pull/72
- add tide configuration for ibm-cloudctl-operator
Fixes #
```release-note
```

onboard ibm-cloudctl-operator.

---

prow/cluster/jobs/IBM/common-service-operator/IBM.common-service-operator.master.yaml

The coverage token secret name for `https://github.com/IBM/common-service-operator` should be `common-service-operator-codecov-token` instead of `ibm-common-service-operator-codecov-token`
Fixes #
```release-note
```

fix incorrect secret name for coverage token.

---

prow/config.yaml

Support run prow job in power platform.
Currently `quay.io` doesn't support multi-arch image without suffix, so we use `docker.io` temporarily.
Fixes #
```release-note
```

support multiarch build.

---

prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/OWNERS

resolve: https://github.com/IBM/operand-deployment-lifecycle-manager/issues/241
**We have add power and s390x cluster to the prow, now we can support real multi-arch build, this PR is to replace the old QEMU simulation way.**
/hold
/dot-not-merge
until the stakeholder approve this to avoid build CI jobs down.
Fixes #
/cc @gyliu513 @chenzhiwei @DanielXLee @horis233
```release-note
```

support real multi-arch build for operand-deployment-lifecycle-manager.

---

prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml

remove power and Z tests for the three repos, as they need `kubebuilder`, `etcd` and `kube-apiserver`, and they are missing for power and Z env.
Will add these prow jobs back after I build new build-tool image with `kubebuilder`, `etcd`, `kube-apiserver`
Fixes #
```release-note
```

remove power and Z tests.

---

prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml

previous build tool had go version 1.13.8 with vulnerabilities, new one has 1.14.6 which is ok
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40090
This PR change only image versions for build-tool
```release-note
new prow build needs to be build in case to have newer golang version for operator
```

update build tool version for License Service

---

prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml

previous build tool had go version 1.13.8 with vulnerabilities, new one has 1.14.6 which is ok
**CVEs: (details as of the time of ADV creation)**
**CVEID: CVE-2020-15586**
Description: Go before 1.13.13 and 1.14.x before 1.14.5 has a data race in some net/http servers, as demonstrated by the httputil.ReverseProxy Handler, because it reads a request body and writes a response at the same time.
CVSS Base Score: 7.5
CVSS Temporal Score: https://exchange.xforce.ibmcloud.com/vulnerabilities/185446 for more information
CVSS Vector: (CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H)
**CVEID: CVE-2020-14039**
Description: In Go before 1.13.13 and 1.14.x before 1.14.5, Certificate.Verify may lack a check on the VerifyOptions.KeyUsages EKU requirements (if …

update build && check tool version for installer repos

---

prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml

previous build tool had go version 1.13.8 with vulnerabilities, new one has 1.14.6 which is ok
```
new prow build needs to be build in case to have newer golang version for operator
```

update build tool version for ibm-auditlogging-operator

---

prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml

Since the ODLM testing requires the kubebuilder and there is no proper kubebuilder binary on power (no etcd binary) and Z environment, I create this PR to remove the testing on them. 
/assign @morvencao
Fixes #
```release-note
```

Remove testing on power and z for ODLM

---

prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml

Since the ibm secretshare operator builds the go binary during the image build, the build jobs in the prow should be removed.
/assign @morvencao 
@morvencao Just want to confirm, Is there the only place I need to update to disable these jobs? How long will it take effect?
Fixes #
```release-note
```

remove build jobs for secretshare

---

common/Makefile.common.mk
prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml

Since ODLM unit test needs kubebuilder and kubebuilder is included in the image`build-tool`, I update the ODLM code coverage job to use `quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05` as the job image.
@morvencao Please correct me if my update is wrong.
/cc @chenzhiwei @DanielXLee
/assign @morvencao 
Fixes #
```release-note
```

using build-tool as the code coverage job image

---

prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml

Verifying update to helm 3 https://github.com/IBM/test-infra/pull/260
Fixes #
```release-note
NONE
```

updated build tool and check tool images for platform-api-operator

---

prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-4.0.yaml

create release 4.0 branch for licensing operator

---

prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.8.yaml

create IBM.ibm-iam-operator.release-3.8.yaml to enable build for 3.8 branch

---

prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.8.yaml

build metering operator for EUS fixpack

enable release-3.8 for metering

---

prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-eus.yaml

- release-cd
- release-efix
- release-eus
removed release-3.8 branch from builds
**What this PR does / why we need it**: To work with new CICD pipeline
Fixes #
```release-note
```

added new branches for ibm-platform-api-operator builds

---

prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml

**What this PR does / why we need it**: 
Multiarch goal builds latest on every release branch, we want to build it only on master.
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48788

Add specific goal to build latest only on master

---

prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.main.yaml

Fix branch names in configuration for [`IBM/crossplane-kubernetes-provider`](https://github.com/IBM/crossplane-provider-kubernetes) repo.
Remove `check_crossplane-provider-kubernetes`.
https://github.ibm.com/ibmprivatecloud/roadmap/issues/50564
```release-note
NONE
```

Fix branch name in configuration for crossplane-provider-kubernetes

---

prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.main.yaml
prow/config.yaml

Create prow build configuration for [IBM/crossplane-provider-ibm-cloud](https://github.com/IBM/crossplane-provider-ibm-cloud) repo.
Fix mismatchen branch names in configuration for [IBM/crossplane-provider-kubernetes](https://github.com/IBM/crossplane-provider-kubernetes) repo.
Add crossplane provider configurations to config.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51087
https://github.ibm.com/ibmprivatecloud/roadmap/issues/50564
```release-note
NONE
```

Add prow configurations for crossplane providers

---

prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml

Prow builds fail due to older Go version.
Fixes 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51354
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50564
```release-note
```

Bump Go version to 1.16.6 for Crossplane Providers

---

prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml

We are removing dependendcy on ppc64le and s390x clusters, but here on development i just want to disable always run to not run these submits on other branches
Fixes [#49256](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49256)
```release-note
```

Remove always_run from development submits

---

prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml

This PR intends to optimize/extend build process by removing redundant jobs and extending existing ones.
- removed redundant jobs (part of the logic moved to operator repo in form of GitHub Workflows)
- enabled dev jobs on all non-official branches
- enabled building images on all branches
- disabled builds when only documentation is changed
This PR is a part of build improvements for LS Operator: [#50988](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50988)
/cc @gyliu513 @ashank07 @xcliu-ca
1. Please confirm that if …

Improve build process / refactor existing jobs

---

prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml

Enabling LSTR pipeline for security audit
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53966
```release-note
```

security audit  release-ltsr pipeline enablement  #53966

---

prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml

`check_ibm-crossplane-operator_postsubmit` job in https://github.com/IBM/ibm-crossplane-operator is constantly failing due to not being able to pull image of check-tool - this commit is bumping tag of check-tool image
Fixes #
```release-note
```

bump check-tool in crossplane

---

prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml

This PR will remove the EUS branch from build defintions of nginx ingress.  This should be fine as EUS is now out of support, but is mainly being done as a test to verify connection to new prow server.

Disable EUS branch of nginx as test

---

prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml

Temporarily disable prow jobs for grafana operator, till we have way to configure ssh keys to connect to GHE

temporarily disable grafana prow jobs (ssh key config issue)

---

prow/cluster/jobs/IBM/ibm-user-management-operator/IBM.ibm-user-management-operator.master.yaml

Fix the branch used to run the ibm-user-management-operator builds

Update ibm-user-management-operator build branch

---

prow/docker/build-tool/Dockerfile
prow/docker/check-tool/Dockerfile

Previously, GOSUMDB was set to "https://sum.golang.org". The "https://" breaks verification, so changing this to sum.golang.org clears up "malformed verifier id" errors.

Fix GOSUMDB value

---

prow/cluster/jobs/IBM/ibm-user-management-operator/IBM.ibm-user-management-operator.master.yaml

Required multiarch generation of the ibm-user-management-operator
Fixes # 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67077
```release-note
```

update ibm-user-managmement for multi arch
